# -*- coding: utf-8 -*-
"""manager_of_projects.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ype2jBnHGsZibgn_HyQvr0sF897l4wXA
"""

def load_notes():
    notes = []
    with open("notes.txt", "r", encoding="utf-8") as f:
            notes = [line.strip() for line in f.readlines()]

    return notes


def save_notes(notes):
    with open("notes.txt", "w", encoding="utf-8") as f:
        for note in notes:
            f.write(note + "\n")


def create(notes):
    note = input("Введите текст для заметки: ").strip()
    if note:
        notes.append(note)
        save_notes(notes)
        print("Заметка добавлена.")


def delete(notes):
        num = int(input("Введите номер заметки для удаления: "))
        if 1 <= num <= len(notes):
            deleted = notes.pop(num - 1)
            save_notes(notes)
            print(f"Заметка '{deleted}' удалена.")
        else:
            print("Некорректный номер.")


def search(notes):
    keyword = input("Введите слово для поиска: ").strip()
    found = [note for note in notes if keyword.lower() in note.lower()]
    if not found:
        print("Совпадений не найдено.")
    else:
        print("Найденные заметки:")
        for note in found:
            print(f"- {note}")


def show(notes):
    if not notes:
        print("Нет заметок.")
        return
    for i, note in enumerate(notes, start=1):
        print(f"{i}. {note}")


def close():
    print("Пока :)")
    exit()

# Интерфейс программы
def interface():
    notes = load_notes()
    print("Привет, я менеджер твоих заметок!")
    while True:
        print('''\nВот список доступных команд:
    1 - создать заметку
    2 - удалить заметку
    3 - найти заметку
    4 - закрыть
    5 - показать все заметки
Введите номер выбранной команды:''')

        answer = input().strip()
        match answer:
            case "1":
                create(notes)
            case "2":
                delete(notes)
            case "3":
                search(notes)
            case "4":
                close()
            case "5":
                show(notes)
            case _:
                print("Введен неправильный запрос.")

# Запуск
if __name__ == "__main__":
    interface()